spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/keyword;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show-sql: true   #하이버네이트 옵션, spl 로그에 찍기
        format-sql: true  #하이버네이트 옵션, spl 줄맞춤해서 로그에 찍기


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace